spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 180454267272-kmphkbua49gd5t9urc8mfpv44cd9me0h.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope: profile, email
            authorization-grant-type: authorization_code
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo