#spring:
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: huseynmamedov472@gmail.com
#    password: yunhntrkwusgjemw
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#          connection-timeout: 5000
#          timeout: 5000
#          write timeout: 5000