server:
  port: 8070

spring:
  profiles:
    include: db,google,mail,ssl,chatgtp
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwtSecret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9123saddsaA2sdGgfsa
jwtExpirationInMs: 36000000
refreshTokenExpiration: 60000000

jwt:
  secret: ${jwtSecret}
  expirationInMs: ${jwtExpirationInMs}
  refreshTokenExpiration: ${refreshTokenExpiration}

file:
  allowed-extensions: jpg,jpeg,gif,ico,png
  # Перечисляем допустимые расширения для файлов изображений

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

web:
  resources:
   static-locations: classpath:/static/

image-url-prefix: https://35.173.133.91:8443/